---

- name: Install docker if not installed
  block:
  - name: Pull nginx image image
    docker_image:
      name: "{{ nginx.docker_image }}"
      source: pull

  - name: Start docker nginx container
    docker_container:
      name: "{{ nginx.container_name }}"
      image: "{{ nginx.docker_image }}"
      ports:
      - "{{ nginx.container_port }}:80"
  when: 
  - docker_exists.rc == 0
  - service_running.rc != 0
