---

- name: Install docker if not installed
  block:
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Add Docker Repository
    apt_repository:
      repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
      state: present
  - name: Update apt and install docker-ce
    apt: 
      update_cache: yes
      name: docker-ce
      state: "{{ docker_version }}"
  - name: Install Docker Module for Python
    pip:
      name: docker
  when:
  - docker_exists.rc != 0 or docker_upgrade
  - ansible_facts['os_family'] == 'Debian'
